name: Run auto update
on:
  push:
    branches:
      - master

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run auto update
        run: ./gradlew upgradeDependencies
        env:
          gitHubWriteToken: ${{ secrets.APP_GITHUB_TOKEN }}
          gitHubUserEmail: ${{ secrets.APP_GITHUB_EMAIL }}
